spring.application.name=ems
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
#server.servlet.context-path=/ems
logging.level.org.springframework=INFO
logging.level.com.example.ems=DEBUG
logging.level.org.springframework.security=DEBUG
